"""
Test Runner Service
Executes AI-generated test cases against user code.

Each test case from Bob has an 'executable_code' field containing
Python assert statements. We run them in a subprocess against the
user's code (injected as module context) with a strict timeout.

Never claims a test passed without actually running it.
"""

import asyncio
import sys
import os
import tempfile
import textwrap
import subprocess
from typing import List

TEST_TIMEOUT = 10  # seconds per test


class TestRunner:
    """
    Executes test cases generated by Bob Shell against user code.
    """

    async def run_tests(self, user_code: str, test_cases: list) -> List[dict]:
        """
        Run a list of test cases against user_code.

        Each test_case dict should have:
          - name: str
          - description: str
          - executable_code: str  (Python code with assert statements)

        Returns a list of result dicts:
          {
            "name": str,
            "description": str,
            "passed": bool,
            "error": str or None,
            "stdout": str,
            "stderr": str,
            "skipped": bool,
            "skip_reason": str or None,
          }
        """
        if not test_cases:
            return []

        results = []
        for tc in test_cases:
            result = await self._run_single_test(user_code, tc)
            results.append(result)
        return results

    async def _run_single_test(self, user_code: str, test_case: dict) -> dict:
        """Run a single test case in an isolated subprocess."""
        name = test_case.get("name", "unnamed_test")
        description = test_case.get("description", "")
        executable_code = test_case.get("executable_code", "").strip()

        base_result = {
            "name": name,
            "description": description,
            "passed": False,
            "error": None,
            "stdout": "",
            "stderr": "",
            "skipped": False,
            "skip_reason": None,
        }

        # Skip tests that are placeholders / comments only
        if not executable_code or executable_code.startswith("#"):
            base_result["skipped"] = True
            base_result["skip_reason"] = "No executable test code provided."
            return base_result

        # Build the test script: inject user code, then run the test
        test_script = _build_test_script(user_code, executable_code)

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as f:
            f.write(test_script)
            tmp_path = f.name

        try:
            def execute_test():
                return subprocess.run(
                    [sys.executable, tmp_path],
                    capture_output=True,
                    text=True,
                    timeout=TEST_TIMEOUT,
                    encoding="utf-8",
                    errors="replace",
                )

            result = await asyncio.to_thread(execute_test)

            stdout = result.stdout or ""
            stderr = result.stderr or ""
            exit_code = result.returncode

            base_result["stdout"] = stdout
            base_result["stderr"] = stderr

            if exit_code == 0:
                base_result["passed"] = True
            else:
                error_msg = _extract_error(stderr)
                base_result["error"] = (
                    error_msg or f"Test failed (exit code {exit_code})."
                )

            return base_result

        except subprocess.TimeoutExpired:
            base_result["error"] = f"Test timed out after {TEST_TIMEOUT}s."
            return base_result

        except Exception as e:
            base_result["error"] = f"Runner error: {e}"
            return base_result
        finally:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


def _build_test_script(user_code: str, test_code: str) -> str:
    """
    Combine user code + test code into a runnable script.

    Strategy: execute user code in exec() to define its globals,
    then run the test code in the same namespace.
    This handles both script-style code (no functions) and module-style code.
    """
    # We use a wrapper that:
    # 1. Defines a namespace
    # 2. exec()s the user code into it
    # 3. Injects the namespace into global scope
    # 4. exec()s the test code
    script = textwrap.dedent(f"""\
    import sys

    _user_code = {repr(user_code)}
    _test_code = {repr(test_code)}

    _ns = {{}}
    try:
        exec(compile(_user_code, '<user_code>', 'exec'), _ns)
    except SystemExit:
        pass
    except Exception as _e:
        # User code itself raised an error — that's a test failure
        print(f"USER CODE ERROR: {{_e}}", file=sys.stderr)
        sys.exit(1)

    # Make user-defined names available at module level for the test
    globals().update({{k: v for k, v in _ns.items() if not k.startswith('__')}})

    try:
        exec(compile(_test_code, '<test_code>', 'exec'), {{**globals(), **_ns}})
    except AssertionError as _ae:
        print(f"AssertionError: {{_ae}}", file=sys.stderr)
        sys.exit(1)
    except Exception as _e:
        print(f"{{type(_e).__name__}}: {{_e}}", file=sys.stderr)
        sys.exit(1)
    """)
    return script


def _extract_error(stderr: str) -> str:
    """Extract the most relevant error line from stderr."""
    if not stderr.strip():
        return ""
    lines = [l.strip() for l in stderr.strip().splitlines() if l.strip()]
    # Return last non-empty line (usually the error message)
    return lines[-1] if lines else stderr[:200]
